name: Python Code Verification Workflow

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-code:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Vous pouvez changer la version si nécessaire

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-html

      # Étape 4 : Analyser le code avec flake8
      - name: Run static code analysis (flake8)
        run: |
          mkdir -p reports
          flake8 . --output-file=reports/flake8-report.txt
        continue-on-error: true  # Ne pas arrêter le workflow même si des erreurs sont détectées

      # Étape 5 : Exécuter les tests avec pytest
      - name: Run tests with pytest
        run: |
          pytest --junitxml=reports/test-report.xml --html=reports/test-report.html

      # Étape 6 : Générer un rapport des artefacts
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: python-code-reports
          path: reports/
